### ISSUE TITLE
package testthat loaded prior to context()

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#10]
After loading cogscimodels with devtools::load_all(), I was not able to execute context("cpt"). It seems that loading cogscimodels doesn't automatically load the testthat package, right?
After loading the testthat package manually, context("cpt") could be executed.

**Comment by FlorianSeitz** [comment]
Of course, this is related to #13 - the testthat package could not have been loaded as load_all() didn't work.

**Comment by JanaJarecki** [comment]
The `context` function is only for internal use in the `test_that` package (it labels a failed test by the context). 

I think the question resolved itself. Since this issue is a developer-only issue I will not fix it and close it. Feel free to re-open if this continues to be an issue
