### ISSUE TITLE
library error 

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#11]
https://github.com/JanaJarecki/cogscimodels/blob/5c6ee7b67d0b6732ad6d8849e551ec27ea4e82a5/tests/testthat/test_cpt.R#L2

I strongly guess this should be library(cogscimodels)

**Comment by JanaJarecki** [comment]
Thank you for the bug report -- please merge the latest development version into the test branch, should be fixed now
