### ISSUE TITLE
cpt predictive testing works except for lowest boundaries

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#21]
results of cog sci models for predictive testing when one parameter changes match the results from http://prospect-theory.behaviouralfinance.net/cpt-calculator.php, except for one case -- when the parameter takes the **lowest possible boundary**

in the line referred below, if you change 1:ncol(pars) (pars is a matrix of lower and upper parameter values) to 2:ncol(pars), everything should work fine.
https://github.com/JanaJarecki/cogscimodels/blob/5446e020c3f9196e7207be5512ef291d29eaa392/tests/testthat/test_cpt.R#L38

**Comment by FlorianSeitz** [comment]
I actually however think the bug is in the cpt calculat (see the link above). Try the following:
for the gamble (100, 1; 0) use the standard parameters, but then turn alpha down to .1, .01, and 0. The cpt value approaches 1, but strangely goes up to 4.6 if alpha = 0.

**Comment by JanaJarecki** [comment]
alpha, beta, gamman, gammap > 0.001
