### ISSUE TITLE
setting parameter to NA is not yet implemented

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#22]
https://github.com/JanaJarecki/cogscimodels/blob/b3168b59a38bcf1951db1044cd551a73b6eb8897/tests/testthat/test_cpt.R#L52

In the error it says you might want to implement that at a given point of time. How shall I proceed? Should I use the expect_error function for now, as one cannot set a parameter to NA?

**Comment by JanaJarecki** [comment]
alles auf 1
