### ISSUE TITLE
cpt seems to not be able to handle one-row matrices

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#23]
One-row data frames work perfectly, however, cpt makes vectors in case of one-row matrices.
https://github.com/JanaJarecki/cogscimodels/blob/21572865377c90d8c78798628928af3cac05c944/tests/testthat/test_cpt.R#L72

**Comment by JanaJarecki** [comment]
> Make an error that matrices aren't allowed
