### ISSUE TITLE
Constraints not working for alpha = "beta"

### ISSUE THREAD

**Issue by JanaJarecki** [JanaJarecki/cognitivemodels#48]

**Comment by FlorianSeitz** [comment]
Hi @JanaJarecki , I was trying to fit the parameters in cpt, but I was still not able to implement the constraint alpha = "beta". Did you solve this issue and I missed somehow to update/recompile the package or is the issue still on the todo list? :)

**Comment by FlorianSeitz** [comment]
I'm afraid I'll have to reopen this issue, as I still get an error when conducting line 93 of test_cpt.R

res <- cpttest[subject < 1, list(fit_soft = list(fit_cpt_soft(dt = .SD))), by = list(repetition, subject)]

 Error in x[.rowid, ] : subscript out of bounds (line 118 in model-cpt.R)
