### ISSUE TITLE
ebm_j: error in utils_constraints

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#49]
Error in apply(A[, 1:m], 1, function(x) max(abs(x)) <= tol) : 
  dim(X) must have a positive length 

dt <- data.frame(
  f1 = c(1, 1, 2, 2),
  f2 = c(1, 2, 1, 2),
  rp = c(12, 14, 14, 16),
  c = c(10, 20, 5, 15),
  c2 = c(1, 1, 2, 2)) 
M <- ebm_j(rp ~ f1 + f2, ~c, data = dt, fix = NULL, choicerule = "none", options = list(fit = FALSE))

**Comment by JanaJarecki** [comment]
solved, I forgot which commit this was hehe
