### ISSUE TITLE
ebm_j partial feedback: if first trial is NA, predictions are not correct

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#63]
https://github.com/JanaJarecki/cognitivemodels/blob/dd3ab9757f1c25a5373f8acd29fe5a841165d6a6/tests/testthat/test_ebmj.R#L228

**Comment by JanaJarecki** [comment]
test rcpp function with init arg, the reason is the Na to 0 conversion
