### ISSUE TITLE
sum constraints

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#67]
Hi Jana

Am I correct that the current version of cognitivemodels does not allow for sum constraints (e.g., in the gcm: lambda = "f1" + "f2" + "f3"). The study I want to use for the parameter recovery of the ebm_j model fits these parameters exactly in this way (sum of the attention weights equals sensitivity parameter).

Best,
Florian

**Comment by JanaJarecki** [comment]
Correct!
