### ISSUE TITLE
default parameters for gcm

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#71]
Hi Jana

Ich bin mir nicht sicher, ob wir bereits darüber gesprochen haben, aber ich habe mich gerade gefragt, ob es nicht schlauer wäre, die default parameters beim GCM so zusetzen, dass sie das Model kleinstmöglich beeinflussen. 

Momentan ist default: equal weighting, lambda = 0.5, r = 1.5, q = 1.5, equal category bias
Mein Vorschlag: equal weighting, **lambda = 1, r = 1, q = 1**, equal category bias

Lambda, r und q würden so keinen Einfluss haben, was mir irgendwie sinnvoll erscheint für einen Default. Wir könnten den Default so sehr gut rechtfertigen (ich beziehe mich hier insbesondere auf einen Reviewer, der meinte, dass wir erklären sollen, woher die Defaults stammen). Was meinst du?

**Comment by JanaJarecki** [comment]
The default parameters in the model are the values that the numeric optimizer uses as starting values for the optimization. Do you think we gain accuracy (or speed) in the optimization by setting the parameters to 1?At this point in time,  I dont know. I guess that the todo here would be to implement timings for the parameter estimation across different data sets and check which starting values yield shortest estimation times. But this seems like a huge project.
