### ISSUE TITLE
failed ti install in Mac OS Big Sur 11.6.6

### ISSUE THREAD

**Issue by jesuscgaliano** [JanaJarecki/cognitivemodels#86]
ERROR: lazy loading failed for package ‘cognitivemodels’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/cognitivemodels’
Warning messages:
1: In i.p(...) : installation of package ‘rgl’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/nk/0fr4rt8x5p9dw90m2w2nphww0000gn/T//Rtmpv7tgQQ/file5a3e6bde1d66/cognitivemodels_0.0.12.tar.gz’ had non-zero exit status
> library(cognitivemodels)
Error in library(cognitivemodels) : 
  there is no package called ‘cognitivemodels’
>

**Comment by JanaJarecki** [comment]
Hi,

try to install the rgl package, then restart R completely, then 
re-install the cognitivemodels package

     install.packages("rgl")

Can you report back if that works?
Best,
Jana

**Comment by jesuscgaliano** [comment]
Hi Jana, thanks for your reply, I've done! but it does not work (: 

Best,
Jesús

Output lines just before installing:

installing to /Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-cognitivemodels/00new/cognitivemodels/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (cognitivemodels)
> library(cognitivemodels)
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so, 6): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgl/libs/rgl.so
  Reason: image not found
Error: package or namespace load failed for ‘cognitivemodels’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: rgl.init(initValue, onlyNULL)
  error: OpenGL is not available in this build
Además: Warning messages:
1: 	Loading rgl's DLL failed. 
	This build of rgl depends on XQuartz, which failed to load.
 See the discussion in https://stackoverflow.com/a/66127391/2554330 
2: Trying without OpenGL... 
>

**Comment by jesuscgaliano** [comment]
Hi Jana, I think it works fine after updating RStudio and R
Thanks again

**Comment by JanaJarecki** [comment]
Hi, thanks for updating!
