### ISSUE TITLE
EBM uses the choicerule parameter falsly as bias parameter

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#9]
https://github.com/JanaJarecki/cogscimodels/blob/5c6ee7b67d0b6732ad6d8849e551ec27ea4e82a5/R/ebm.R#L207

Is the choice rule parameter mistaken as bias b?

**Comment by JanaJarecki** [comment]
The constraints use the choicerule parameter as well, > fix the sum constraint
